---
apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: tiltak-hendelse-aktivitetsplan-alerts
  namespace: team-tiltak
  labels:
    team: team-tiltak
spec:
  receivers:
    slack:
      channel: arbeidsgiver-tiltak-alerts
      prependText: '<!here> | '
  alerts:
    - alert: Applikasjon nede
      expr: sum(up{app="tiltak-hendelse-aktivitetsplan", job="kubernetes-pods"}) == 0
      for: 2m
      description: "App {{ $labels.log_app }} er nede i namespace {{ $labels.kubernetes_namespace }}"
      action: "`kubectl describe pod {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for logger"
    - alert: Det har skjedd en feil i tiltak-hendelse-aktivitetsplan, logget med level Error
      expr: sum(increase(logd_messages_total{log_app="tiltak-hendelse-aktivitetsplan",log_level="Error"}[10m])) > 0
      for: 10s
      description: "tiltak-hendelse-aktivitetsplan har logget en feil"
      action: "Sjekk logs.adeo.no for logger"
