apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "tiltak-hendelse-aktivitetsplan"
  namespace: "team-tiltak"
  labels:
    "team": "team-tiltak"
spec:
  azure:
    application:
      enabled: true
  kafka:
    pool: {{kafka-pool}}
  image: {{image}}
  ingresses:
    - {{ingress}}
  liveness:
    path: "/tiltak-hendelse-aktivitetsplan/internal/isAlive"
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/tiltak-hendelse-aktivitetsplan/internal/isReady"
    initialDelay: 20
    timeout: 60
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: "400Mi"
    requests:
      cpu: "150m"
      memory: "320Mi"
  gcp:
    sqlInstances:
    - type: POSTGRES_14
      tier: {{db-tier}}
      databases:
        - name: tiltak-hendelse-aktivitetsplan-db
          envVarPrefix: DB
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  accessPolicy:
    inbound:
      rules:
        - application: tiltaksgjennomforing-api
          namespace: arbeidsgiver
          cluster: {{tiltaksgjennomforing-cluster}}
