apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "tiltak-hendelse-aktivitetsplan"
  namespace: "team-tiltak"
  labels:
    "team": "team-tiltak"
spec:
  kafka:
    pool: {{kafka-pool}}
  image: {{image}}
  liveness:
    path: "/tiltak-hendelse-aktivitetsplan/internal/isAlive"
    port: 8092
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/tiltak-hendelse-aktivitetsplan/internal/isReady"
    port: 8092
    initialDelay: 20
    timeout: 60
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  gcp:
    sqlInstances:
    - type: POSTGRES_14
      tier: {{db-tier}}
      databases:
        - name: tiltak-hendelse-aktivitetsplan-db
          envVarPrefix: DB