apiVersion: "kafka.nais.io/v1"
kind: "Topic"
metadata:
  name: "arbeidsgiver.tiltak-avtale-hendelse"
  namespace: "team-tiltak"
  labels:
    "team": "team-tiltak"
    "start.nais.io/created-by": "me"
    "start.nais.io/creationTimestamp": "2022-10-19T04:24:54.264635067"
spec:
  pool: "${{kafkaPool}}"
  config:
    cleanupPolicy: "delete"
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 72
  acl:
  - team: "team-tiltak"
    application: "tiltak-hendelse-aktivitetsplan"
    access: "readwrite"
  - team: "anotherteam"
    application: "anotherapp"
    access: "read"